---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-concourse-flux
  name: helloworld
  labels:
    app: helloworld
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.helloworld: semver:~1.0
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      namespace: demo-concourse-flux
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: particule/demo-concourse-flux:1.0.7
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: demo-concourse-flux
  name: helloworld-svc
spec:
  ports:
  - port: 80
  selector:
    app: helloworld
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: demo-concourse-flux
  name: helloworld
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: demo-concourse-flux.particule.io
    http:
      paths:
      - backend:
          serviceName: helloworld-svc
          servicePort: 80
